### ISSUE TITLE
Unable to run Stan file

### ISSUE THREAD

**Issue by ruben-a** [carolinecolijn/distancing-impact-covid19#1]
I am trying to replicate your model but I  have not been able to run your stan file. I've tested rstan package running a simple model and it works. I am wondering if anyone else has had the same issue.

This is the error I get. Thanks

Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: file2e58550e4716.o:file2e58550e4716.cpp:(.text$_ZN4stan4math17cvodes_integratorILi2EE9integrateIN34model2e584a6276e6_seeiqr_namespace16seeiqr_functor__EddEESt6vectorIS6_INS_11return_typeIT0_JT1_EE4typeESaISB_EESaISD_EERKT_RKS6_IS8_SaIS8_EEdRKS6_IdSaIdEERKS6_IS9_SaIS9_EESQ_RKS6_IiSaIiEEPSoddl[_ZN4stan4math17cvodes_integratorILi2EE9integrateIN34model2e584a6276e6_seeiqr_namespace16seeiqr_functor__EddEESt6vectorIS6_INS_11return_typeIT0_JT1_EE4typeESaISB_EESaISD_EERKT_RKS6_IS8_SaIS8_EEdRKS6_IdSaIdEERKS6_IS9_SaIS9_EESQ_RKS6_IiSaIiEEPSoddl]+0x26d): undefined reference to `N_VMake_Serial'
C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: file2e58550e4716.o:file2e58550e4716.cpp:(.text$_ZN4stan4math17cvodes_integratorILi2EE9integrateIN34model2e584a6276e6_seeiqr_namespace16seeiqr_
Error in sink(type = "output") : invalid connection

**Comment by seananderson** [comment]
I'm not sure, although Google makes me think it could have to do with the Stan ODE solver and incompatibility with something in the C++ compiling chain.

Are you on a recent version of R, Windows rtools, and rstan?

Does the following return `TRUE`?

```r
pkgbuild::has_build_tools(debug = TRUE)
```

Are you able to install this: https://github.com/seananderson/covidseir which is a newer R package version of this model with some added functionality and examples?

**Comment by ruben-a** [comment]
Thanks for taking the time  to look into this.
re your questions:
I have the latest version available  
pkgbuild::has_build_tools(debug = TRUE)  returns true
and I was able to install the covidseir package 

I tried reinstalling the packages but still get the same error.

**Comment by seananderson** [comment]
If the package installs but not this, then I wonder if the problem is the ODE solving function combined with the specific C++ compiler chain because that is different between the two.

You could try this branch I just started:
https://github.com/carolinecolijn/distancing-impact-covid19/tree/rk45

The diff: https://github.com/carolinecolijn/distancing-impact-covid19/commit/9cfb0a254fa962c44bb42d45be04945a34762e07

In general, the package is more well thought out and also works with multiple types of case data. The code in this repository is older and was written before the package.

**Comment by ruben-a** [comment]
That was it. I am able to run it. Thanks a lot Sean for taking the time and thinking this through. I really appreciate it. I spent a couple of nights unsuccessfully trying to find what the issue was.
